export const LIST_PROFILE_REQUESTED = "spotify/LIST_PROFILE_REQUESTED";
export const LIST_PROFILE_FULFILLED = "spotify/LIST_PROFILE_FULFILLED";
export const LIST_PROFILE_REJECTED = "spotify/LIST_PROFILE_REJECTED";

export const SEARCH_MUSIC_REQUESTED = "spotify/SEARCH_MUSIC_REQUESTED";
export const SEARCH_MUSIC_FULFILLED = "spotify/SEARCH_MUSIC_FULFILLED";
export const SEARCH_MUSIC_REJECTED = "spotify/SEARCH_MUSIC_REJECTED";

export const LIST_ALBUM_REQUESTED = "spotify/LIST_ALBUM_REQUESTED";
export const LIST_ALBUM_FULFILLED = "spotify/LIST_ALBUM_FULFILLED";
export const LIST_ALBUM_REJECTED = "spotify/LIST_ALBUM_REJECTED";

export const LIST_TRACKS_REQUESTED = "spotify/LIST_TRACKS_REQUESTED";
export const LIST_TRACKS_FULFILLED = "spotify/LIST_TRACKS_FULFILLED";
export const LIST_TRACKS_REJECTED = "spotify/LIST_TRACKS_REJECTED";

export const LIST_MUSIC_REQUESTED = "spotify/LIST_MUSIC_REQUESTED";
export const LIST_MUSIC_FULFILLED = "spotify/LIST_MUSIC_FULFILLED";
export const LIST_MUSIC_REJECTED = "spotify/LIST_MUSIC_REJECTED";
